### ISSUE TITLE
Cypress support

### ISSUE THREAD

**Issue by akauppi** [akauppi/firebase-custom-builder#3]
One cannot run Cypress on this image, since it's Alpine based.

There are loads of discussions online about making smaller Cypress images, for CI needs.

- Cypress.io point is that a "slim image" is not needed, since CI systems do caching.
- There is a Debian slim -based image (of 1.3 GB) in [one of the PRs](https://github.com/cypress-io/cypress-docker-images/pull/276#issuecomment-703224769).

**Strategy**

The author is currently not in a huge need for such an image.

Check again, when these two have progressed:

- https://github.com/cypress-io/cypress/issues/3899
- https://github.com/cypress-io/cypress/issues/16505

**Comment by smccarthy-godaddy** [comment]
Following this issue 🤞

**Comment by akauppi** [comment]
@smccarthy-godaddy Just a heads up for you: 

I am trying out Docker Compose, allowing to mix the Firebase Emulators (Alpine based) and `cypress/included:8.0.0` (Debian based) in the same application project. This work may take some time but at the moment it seems that I don't need to make an Alpine-based Cypress image.

---

You can follow that work in https://github.com/akauppi/GroundLevel-firebase-es/issues/75

**Comment by akauppi** [comment]
@smccarthy-godaddy Got it done - and it works.
